// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z
	.object({
		UPDATE_BEARER_KEY: z.string(),
		GITHUB_APP_KEY: z.string(),
		GH_SESSION_TOKEN: z.string(),
	})
	.parse(process.env);

export default env;
